config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
 
  resources :arts do
    resources :resumes
  end

   root 'welcome#index'
   # resources :resumes, only: [:index, :new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/art.rb
class Art < ApplicationRecord
	 has_many :resumes
	validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/resume.rb
class Resume < ApplicationRecord
	 mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
   validates :name, presence: true # Make sure the owner's name is present.
   belongs_to :art
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController	
	def new
        @art = Art.new
	end	
	def edit
		@art = Art.find(params[:id])
	end
	def index
  	  @art = Art.includes(:resumes)
  	end
	def create
	  @art = Art.new(art_params)
	 
	  if @art.save
	    redirect_to @art
  	  else
		render 'new'
 	 end
	end
	def show
  	  @art = Art.find(params[:id])
 	 end
 	def update
	  @art = Art.find(params[:id])
	 
	  if @art.update(art_params)
		    redirect_to @art
	  else
		    render 'edit'
	  end
	end
	def destroy

	  @art = Art.find(params[:id])
	  @art.destroy
	 
	  redirect_to arts_path
	end 
private
  def art_params
    params.require(:art).permit(:title, :text)
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
      @resumes = Resume.all
   end   
   def new
   	  @art = Art.find(params[:art_id])
      @resume = @art.resumes.new
   end   
   def show
     @resume = Resume.find(params[:id])
    end
   def create
   	  @art = Art.find(params[:art_id])
   	  @resume = @art.resumes.new(resume_params)      
      if @resume.save!
         redirect_to arts_path, notice: "The resume #{@resume.name} has been uploaded."
      else
         render "new"
      end
   end   
   def destroy
      @resume = Resume.find(params[:id])
      @resume.destroy
      redirect_to  welcome_index_path, notice:  "The resume #{@resume.name} has been deleted."
   end   
   private
      def resume_params
      params.require(:resume).permit(:name, :attachment)
   end   
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	 before_action :authenticate_user!
	 before_action :user_signed_in?
	 before_action :current_user
	 before_action :user_session
  def index
  	@resumes = Resume.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/arts/_form.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<% if @art.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@art.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @art.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@art, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-6">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :text %>
   </div>
   <div class="col-sm-6">
    <%= f.text_area :text, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-primary btn-large' %>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/arts/edit.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render 'layouts/navigation' %>
<h1>Edit article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', arts_path, class: "btn btn-xs btn-success" %>

app/views/arts/index.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render 'layouts/navigation' %>
<h1 align="center">Listing all articles</h1>
<% @art.each do |art| %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="article-title">
     <%= link_to art.title, art_path(art) %>
     
    </div>
    <div class="article-body">
     <%= truncate(art.text, length: 100) %>
    </div>
    <div class="article-actions">
      <table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% art.resumes.each do |resume| %>
       <tr>
          <td><%= resume.name %></td>
          <td><%= link_to "Download Resume", resume.attachment_url %></td>
          <td><%= button_to "Delete",art_resume_path(art, resume),  method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
       </tr> 
      <% end %>
   </tbody>
   
</table>
     <%= link_to "Edit", edit_art_path(art), class: "btn btn-xs btn-primary" %>
     <%= link_to "Upload", new_art_resume_path(art), class: "btn btn-xs btn-success" %>
     <%= link_to "Delete", art_path(art), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>

    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/arts/new.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render 'layouts/navigation' %>
<h1>New Articles</h1>

<%= render 'form' %>


<%= link_to 'Back', arts_path, class: "btn btn-xs btn-success" %>

app/views/arts/show.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render 'layouts/navigation' %>
<h2 align="center">Title: <%= @art.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@art.text) %>


<!--ALL BUTTONS-->

<%= link_to "Edit", edit_art_path(@art), class: "btn btn-xs btn-primary" %> ||
<%= link_to "Delete", art_path(@art), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>||
<%= link_to 'Back', arts_path, class: "btn btn-xs btn-success" %>||


<!--Insert image here and display for individual id-->

	

app/views/layouts/_navigation.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Articles", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to 'New art', new_art_path %> <span class="sr-only">(current)</span></li>
        <li> <%= link_to 'My Blog', controller: 'arts' %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Sign In</a></li>
        <li><a href="#">Sign Up</a></li>
        <li><%= link_to 'Log Out', destroy_user_session_path, :method => :delete%></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->  
  <link rel="icon" type="image/png" href="images/icons/favicon.ico"/>
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
<!--===============================================================================================-->  
  <link rel="stylesheet" type="text/css" href="vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
<!--===============================================================================================-->  
  <link rel="stylesheet" type="text/css" href="vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
  <link rel="stylesheet" type="text/css" href="css/util.css">
  <link rel="stylesheet" type="text/css" href="css/main.css">
<!--===============================================================================================-->
    <title>Article</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :javascript_includes %>
  </head>

  <body>
    
    <%= render 'shared/messages' %>
    
    <%= yield %>
  </body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<br />

<%= link_to "New Resume", new_art_resume_path, class: "btn btn-primary" %>
<br />
<br />

<table class = "table table-bordered table-striped">
   <thead>.
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td><%= link_to "Download Resume", resume.attachment_url %></td>
            <td><%= button_to "Delete", art_resume_path(resume.art.id, resume.id), method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class = "alert alert-error">
    <ul>
       <% @resume.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
       <% end %>
    </ul>
  </div>
<% end %>

<div class = "well">
  <%= form_for [:art, @resume], html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/resumes/show.html.erb
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= render 'layouts/navigation' %>
<h2 align="center">Title: <%= @art.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <h4 class="center"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@art.text) %>


<!--ALL BUTTONS-->

<%= link_to "Edit", edit_art_path(@art), class: "btn btn-xs btn-primary" %> ||
<%= link_to "Delete", art_path(@art), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>||
<%= link_to 'Back', arts_path, class: "btn btn-xs btn-success" %>||

app/views/shared/_errors.html.erb
<% if @art.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@art.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @art.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<%= render 'layouts/navigation' %>
<h1 class="article-body">Welcome To Articles</h1>
<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100 p-t-30 p-b-50">
				
				 <table class = "table table-bordered table-striped">
   <thead>
      <tr>
         <th>Name</th>
         <th>Download Link</th>
         <th> </th>
      </tr>
   </thead>
   
   <tbody>
      <% @resumes.each do |resume| %>
         
         <tr>
            <td><%= resume.name %></td>
            <td><%= link_to "Download Resume", resume.attachment_url %></td>
            <td><%= button_to "Delete",art_resume_path(resume.art_id, resume.id),  method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
         </tr>
         
      <% end %>
   </tbody>
   
</table>
				
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/bootstrap/js/popper.js"></script>
	<script src="vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="vendor/daterangepicker/moment.min.js"></script>
	<script src="vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="js/main.js"></script>
 <!--  <#%= link_to 'My Blog', controller: 'arts' %> ||

<#%= link_to 'New art', new_art_path %>
 -->